### ISSUE TITLE
The latest version will cause the hat on the v65 version to be removed

### ISSUE THREAD

**Issue by 1450143535** [ButteryStancakes/ButteryFixes#16]
When I use ButteryFixes (1.10.4) version, the hat on my head does not affect my field of view, but the effect is that the hat on my head is removed and disappeared, which makes the game lose a new thing. When I don't use it, the hat on my head comes back again. Please analyze and modify it again to ensure that the hat is still on my head without affecting my field of view
![769ea5222c34cfdcb891385d3a19e775](https://github.com/user-attachments/assets/43762aeb-0877-4cab-8fee-09490054e26c)

**Comment by ButteryStancakes** [comment]
This is likely caused by the changes I've made to the costumes so they will render properly on the player's shadow. Since you can observe those shadow rendering problems in vanilla, but you can't see your hat outside of using external mods for third person view, I don't plan on changing this - sorry.

These shadow changes also affect the bee and bunny suits, but it has gone unreported for months now, which I think puts into perspective how this issue is fairly minor.

Also, as of v66, the birthday hats have been removed from the game anyway.
