### ISSUE TITLE
Obnoxious ship lighting with HDLethalCompany

### ISSUE THREAD

**Issue by kworpy** [ButteryStancakes/ButteryFixes#19]
I play with HDLethalCompany with all settings at the lowest, and with ButteryFixes, the lighting in the ship is overly bright

without HDLC
![withouthd](https://github.com/user-attachments/assets/122db6fc-5028-4487-9dd8-279e5fc4025a)
with HDLC and no BF
![withhdnobutter](https://github.com/user-attachments/assets/22236345-7200-462a-9898-1cc2079732cd)
with HDLC and BF
![withhdandbutter](https://github.com/user-attachments/assets/a15a31f7-751f-4750-bd19-c05af9aefe1b)

**Comment by CoolLKKPS** [comment]
> @ButteryStancakes a mention, u also need to know this

> @kworpy i create another issue ticket in [here](https://github.com/ButteryStancakes/Chameleon/issues/4), but overall that bc dev make a fake light source when in orbit for immersion, this issue will happen if u disabled the `shadow` entirely, u can see the planet in the monitor.

**but that way still a bit ruin the immersion**, planets should be illuminated by the sun unless planet also have their own light sources, which that's why i sug merge this feature to `Chameleon` mod, and u know, one of my friend really like that light source bc my friend loves the shadows created by this light source, so they can show their custom player model, so i did sug make a config option to let user decide to enable this feature In `Chameleon` mod (if u can, try not to change the sunlight position), and made a in-game sun, BUT not conflict with `Celestial_Tint by sfDesat` (or maybe u can use `Celestial_Tint` sunlight?)

**Comment by ButteryStancakes** [comment]
This feature has been removed in v1.10.9. It is now a config setting that can be enabled/disabled in Chameleon
