### ISSUE TITLE
ButteryFixes and MeleeFixes does not work

### ISSUE THREAD

**Issue by InfiniteHouseplant** [ButteryStancakes/ButteryFixes#3]
Whenever I try to load those two mods when I get into a new save its just a black screen with my ui and the grab prompt.

**Comment by ButteryStancakes** [comment]
I would need your Unity log to be able to tell what your issue is. I messed up v1.4.0 (which causes this crash if you use MoreCompany) but that should be fixed in v1.4.1.

If you are still experiencing trouble in v1.4.1, please let me know and forward your player log (from `%appdata%\..\LocalLow\ZeekerssRBLX\Lethal Company`, file `Player.log`) after you next experience the bug
