### ISSUE TITLE
[Bug] Desynced Weather with Late Joiners

### ISSUE THREAD

**Issue by broken-usb** [ButteryStancakes/ButteryFixes#9]
It seems like the "randomize starting seed" can cause weather desync under specific circumstances.
### How to reproduce(i think):
- Required mods: [ButteryFixes](https://thunderstore.io/c/lethal-company/p/ButteryStancakes/ButteryFixes/) and [LobbyControl](https://thunderstore.io/c/lethal-company/p/mattymatty/LobbyControl/)
- Start a new save file on a private lobby
- Land on Company Building then go back into orbit
- Change the lobby from Friends Only to Public using Lobby Control
- Change the lobby from Closed to Open using Lobby Control
- Wait for people to join(people who don't have any mods installed)

If those players check their moon list the weather conditions for them will be different(sales will prob be different too).
I had chosen Assurance to go to since for me it was clear weather but everyone else said it was Rainy(wich is the default weather for the starting seed), we ended up changing the route to Vow wich was flooded for me but it was supposedly clean for them.

Sadly, i don't have the log file from when that happend.

**Comment by ButteryStancakes** [comment]
This is a bug caused by late join, not by ButteryFixes.

Landing at The Company changes the game seed, but doesn't call the function to re-randomize weather using the seed. Any clients that join the game after this point will have to randomize weather (since they wouldn't have the previous day's weather data) and they would see weather different from all the clients that were previously connected.

The same does apply to sales, since those are also based on the seed.

Both of these would require additional networking to sync weather/sales directly with the host upon joining, which isn't possible with client-side mods
